### ISSUE TITLE
Singularity installation fails

### ISSUE THREAD

**Issue by elcortegano** [filtho/ContrastiveLosses#7]
I'm trying to install this tool using singularity by running the `apptainer` command as described in the README. However, it fails collecting `bed-reader`. This is the message error: 

> Collecting bed-reader>=0.2.5 (from pysnptools==0.5.7)
  Downloading bed_reader-1.0.5.tar.gz (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 47.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

 > × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

 >   Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

 >   Checking for Rust toolchain....
      [end of output]

>  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

>× Encountered error while generating package metadata.
╰─> See above for output.

>note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
FATAL:   While performing build: while running engine: while running %post section: exit status 1

I have installed cargo (as described [here](https://rustup.rs/)), just in case this fixed the issue, but it does not.

A related, perhaps related error us the following, which appears earlier in my log file. This is a failure from pip to install all packages due to dependency issues.

> Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.10.1
    Uninstalling scipy-1.10.1:
      Successfully uninstalled scipy-1.10.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.4.6 requires scipy>=1.5, but you have scipy 1.4.1 which is incompatible.
Successfully installed scipy-1.4.1

But I am not sure this is relevant to the failure in building the image, since `scipy` seems to be installed despite the error.

**Comment by elcortegano** [comment]
Thanks, this solves the problem of creating the image.

However, the image is not able to reproduce the examples provided in the README. Running any of the examples results in a message indicating that the packages `docopt` and `tensorflow` are not installed. The former can be installed without issue from within the container, but the installation of `tensorflow` breaks.

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.13.1 requires aiohttp<4.0.0,>=3.9.2, which is not installed.
scipy 1.6.2 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.24.3 which is incompatible

**Comment by filtho** [comment]
Hmm, both TensorFlow and docopt should be available from within the container image, once installed correctly. 
The container is built on NVIDIA NGC TensorFlow container (https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow) which has  tensorflow pre-installed. And if building the image returned no errors, then docopt should also be available. You should not have to install any other packages from within the container

How are you using the image? I realize now it doesn't explicitly say how this is done in the README.

To check if the image has TensorFlow installed, you can run this:
`singularity exec image.sif python3.10 -c  "import tensorflow as tf ; print(f'Imported Tensorflow version {tf.__version__}')"
`
This works for me, after having created the image using the updated definition file.

To run the codes, I usually start a shell using the image, from which you should be able to run the code.
This can be done by running: 
`singularity run --nv /path/to/image.sif`

> ================
== TensorFlow ==
================
NVIDIA Release 24.05-tf2 (build 91418384)
TensorFlow Version 2.15.0
Container image Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Copyright 2017-2024 The TensorFlow Authors.  All rights reserved.
Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

And then running, in the gcae folder, for example
`python3 run_gcae.py train --trainedmodeldir=./test  --datadir=Data/dog --model_id=CM_2D_test --data=All_Pure_150k --train_opts_id=ex3_CL --data_opts_id=d_0_4_dog_cont --save_interval=5 --epochs=100`


Or, you can use the image and call the Python script in one line, like this:

`singularity exec --nv  /path/to/image.sif python3 run_gcae.py train --trainedmodeldir=./test  --datadir=Data/dog --model_id=CM_2D_test --data=All_Pure_150k --train_opts_id=ex3_CL --data_opts_id=d_0_4_dog_cont --save_interval=5 --epochs=100`

The --nv flag is to set up the use of cuda-enabled devices, if you have an NVIDIA GPU.

If this does not work, or this is what you already tried I apologize for misunderstanding, please let me know and I can try to help get this sorted out.

**Comment by elcortegano** [comment]
Thanks for the feedback. I can confirm that both `tensorflow` (and `docopt`) are installed in the image by using your `singularity exec` command.

However, when I run the image, and then run `python3 gcae/run_gcae.py` from within the container, the following error message appears:

>Traceback (most recent call last):
  File "/home/elcortegano/CLtest/ContrastiveLosses/gcae/run_gcae.py", line 33, in <module>
    from docopt import docopt, DocoptExit
ModuleNotFoundError: No module named 'docopt'

And if `docopt` is installed, `tensorflow` comes next with the error.

To clarify the issue, the steps I am following are:

    sudo apptainer build image.sif image.def  # no errors (but some warnings)
    apptainer run --nv image.sif  # also tried with singularity, and removing the --nv flag

    Apptainer> python3 ./gcae/run_gcae.py  # this returns the error, which also appears using the full line command with run_gcae.py train. Also tried with python rather than python3

**Comment by filtho** [comment]
Okay, thank you. It does seem weird that the packages can be found in one case, but not when calling the other script. Could it be the case that python3 is an alias for a specific Python version on your machine? 

The image is shipped with Python 3.10.6, and the package installations are done for 3.10, I'm pretty sure. Since the line 
`singularity exec image.sif python3.10 -c  "import tensorflow as tf ; print(f'Imported Tensorflow version {tf.__version__}')" `
worked, where we explicitly state to use python3.10, could you try to run the code with python 3.10? This is the only thing I can think of right now that is different between the two lines.

So, maybe try the following:
` python3.10 ./gcae/run_gcae.py`

Sorry for this  hassle, and thank you for your patience.

**Comment by filtho** [comment]
Great! Now I think it's just a small thing -- there is no argument supplied for --save_interval. Set it to something reasonable in relation to the number of epochs. Saving too often can take up a lot of storage space, depending on the model used.

So, the following should (hopefully) work:

`python3.10 run_gcae.py train --trainedmodeldir=test --datadir=Data/dog --model_id=CM_2D_test --data=All_Pure_150k --train_opts_id=ex3_CL --data_opts_id=d_0_4_dog_cont **--save_interval=5** --epochs=10`

**Comment by elcortegano** [comment]
Now I had the opportunity to test the tool and it works quite well! thank you very much, and congratulations for the new method. It looks promising.

**Comment by filtho** [comment]
Glad to hear you got it working :)
Thank you very much for your patience with this, and for testing it. This was the first time (to my knowledge) it was tested externally, so I'm grateful that you helped me work out the kinks.  I will make sure to update the page to make it more clear.
